jobs:
  build-HSQLDB:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Maven -v
      run: mvn -v
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build with Maven
      run: mvn -Ddatasource.dialect=HSQLDB -B package --file pom.xml
  build-MARIADB_10_1:
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        image: mariadb:10.1
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=5
        ports:
        - 3306:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Maven -v
      run: mvn -v
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Create db
      run: mysql --host=127.0.0.1 -u root -e 'CREATE DATABASE lavagna CHARACTER SET
        utf8 COLLATE utf8_bin;'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -Ddatasource.dialect=MYSQL -B package --file pom.xml
  build-MYSQL-5_5:
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        image: mysql:5.5
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=5
        ports:
        - 3306:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Maven -v
      run: mvn -v
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Create db
      run: mysql --host=127.0.0.1 -u root -e 'CREATE DATABASE lavagna CHARACTER SET
        utf8 COLLATE utf8_bin;'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -Ddatasource.dialect=MYSQL -B package --file pom.xml
  build-MYSQL-5_6:
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        image: mysql:5.6
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=5
        ports:
        - 3306:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Maven -v
      run: mvn -v
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Create db
      run: mysql --host=127.0.0.1 -u root -e 'CREATE DATABASE lavagna CHARACTER SET
        utf8 COLLATE utf8_bin;'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -Ddatasource.dialect=MYSQL -B package --file pom.xml
  build-PGSQL-9_4:
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_DB: lavagna
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        image: postgres:9.4
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Maven -v
      run: mvn -v
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build with Maven
      run: mvn -Ddatasource.dialect=PGSQL -B package --file pom.xml
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
